### PR TITLE
[resolves #88] Request for invalid Tx should fail

### LINKED ISSUE #88: Request for invalid Tx should fail
```
Getting Tx: 853e910bedb7c8213bc93cab7e8337e0a59731db1e0c8968d2e19355d850bdc5
Nov 29, 2018 6:44:36 AM wf.bitcoin.javabitcoindrpcclient.BitcoinJSONRPCClient$TransactionWrapper raw
WARNING: RPC Query Failed (method: getrawtransaction, params: [853e910bedb7c8213bc93cab7e8337e0a59731db1e0c8968d2e19355d850bdc5, 1], response code: 500 responseMessage Internal Server Error, response: {"result":null,"error":{"code":-5,"message":"No information available about transaction"},"id":"1"}

Got Tx: [tx=853e910bedb7c8213bc93cab7e8337e0a59731db1e0c8968d2e19355d850bdc5, vin=0, vout=0]
```

May returns a Tx object that has neither vin nor vout

### PR DESCRIPTION
**Pull request by tdiesler**

### CODE REVIEW

File: src/main/java/wf/bitcoin/javabitcoindrpcclient/BitcoindRpcClient.java [hunk 1]
```diff
@@ -1581,11 +1581,36 @@ public BigDecimal amount() {
     String hash();
 
     /**
-     * get the height of block in which this transaction is</br>
-     * <b>PAY ATTENSION</b> this properties only works with bitcoind nodes of which version is under 0.15
```
Comment (Polve) [inline src/main/java/wf/bitcoin/javabitcoindrpcclient/BitcoindRpcClient.java]: "ATTENTION"

File: src/main/java/wf/bitcoin/javabitcoindrpcclient/BitcoinJSONRPCClient.java [hunk 2]
```diff
@@ -1704,11 +1714,6 @@ public Out getTransactionOutput() {
       public String scriptPubKey() {
         return mapStr("scriptPubKey");
       }
-
-      @Override
-      public String address() {
-          return mapStr("address");
-      }
```
Comment (Polve) [inline src/main/java/wf/bitcoin/javabitcoindrpcclient/BitcoinJSONRPCClient.java]: obsolete method?

Comment (tdiesler) [reply src/main/java/wf/bitcoin/javabitcoindrpcclient/BitcoinJSONRPCClient.java]: Yes, this only works for bitcoind nodes of which version is under 0.15 (see above). Also, now that we provide general map wrapper access it is no longer necessary to to provide a typed API for stuff that is non-standard.
